package io.safelang.compiler.jvm;

import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Builds the constant pool of a JVM class file. Entries are interned so identical constants share a
 * single index. Long and Double entries occupy two pool slots, as the JVM specification requires.
 *
 * <p>Generated SAFE code only ever references ordinary class methods (the {@link
 * io.safelang.compiler.jvm.JvmRuntime} facade and the generated class itself), so the pool needs no
 * {@code InterfaceMethodref} entries. Keeping interface invocation out of generated bytecode is
 * what lets the class file stay at major version 50 and skip {@code StackMapTable} attributes.
 */
final class ConstantPool {

  private final ByteArrayOutputStream bytes = new ByteArrayOutputStream();
  private final DataOutputStream out = new DataOutputStream(bytes);
  private final Map<String, Integer> interned = new LinkedHashMap<>();
  private int next = 1;

  int utf8(final String text) {
    return intern(
        "u:" + text,
        1,
        () -> {
          out.writeByte(Tag.UTF8.tag);
          out.writeUTF(text);
        });
  }

  int integer(final int value) {
    return intern(
        "i:" + value,
        1,
        () -> {
          out.writeByte(Tag.INTEGER.tag);
          out.writeInt(value);
        });
  }

  int longValue(final long value) {
    return intern(
        "l:" + value,
        2,
        () -> {
          out.writeByte(Tag.LONG.tag);
          out.writeLong(value);
        });
  }

  int floatValue(final float value) {
    return intern(
        "f:" + value,
        1,
        () -> {
          out.writeByte(Tag.FLOAT.tag);
          out.writeFloat(value);
        });
  }

  int doubleValue(final double value) {
    return intern(
        "d:" + value,
        2,
        () -> {
          out.writeByte(Tag.DOUBLE.tag);
          out.writeDouble(value);
        });
  }

  int string(final String text) {
    final var utf = utf8(text);
    return intern(
        "s:" + text,
        1,
        () -> {
          out.writeByte(Tag.STRING.tag);
          out.writeShort(utf);
        });
  }

  int classDefinition(final String internal) {
    final var name = utf8(internal);
    return intern(
        "c:" + internal,
        1,
        () -> {
          out.writeByte(Tag.CLASS.tag);
          out.writeShort(name);
        });
  }

  int nameAndType(final String name, final String descriptor) {
    final var nameIndex = utf8(name);
    final var descriptorIndex = utf8(descriptor);
    return intern(
        "nt:" + name + ":" + descriptor,
        1,
        () -> {
          out.writeByte(Tag.NAME_AND_TYPE.tag);
          out.writeShort(nameIndex);
          out.writeShort(descriptorIndex);
        });
  }

  int method(final String owner, final String name, final String descriptor) {
    final var classIndex = classDefinition(owner);
    final var typeIndex = nameAndType(name, descriptor);
    return intern(
        "m:" + owner + ":" + name + ":" + descriptor,
        1,
        () -> {
          out.writeByte(Tag.METHOD_REFERENCE.tag);
          out.writeShort(classIndex);
          out.writeShort(typeIndex);
        });
  }

  int field(final String owner, final String name, final String descriptor) {
    final var classIndex = classDefinition(owner);
    final var typeIndex = nameAndType(name, descriptor);
    return intern(
        "fld:" + owner + ":" + name + ":" + descriptor,
        1,
        () -> {
          out.writeByte(Tag.FIELD_REFERENCE.tag);
          out.writeShort(classIndex);
          out.writeShort(typeIndex);
        });
  }

  /** Total number of pool slots, including the implicit slot 0 (constant_pool_count). */
  int count() {
    return next;
  }

  void writeTo(final DataOutputStream target) throws IOException {
    target.writeShort(next);
    bytes.writeTo(target);
  }

  private int intern(final String key, final int slots, final Emit emit) {
    final var existing = interned.get(key);
    if (existing != null) {
      return existing;
    }
    final var index = next;
    try {
      emit.run();
    } catch (final IOException exception) {
      throw new UncheckedIOException(exception);
    }
    interned.put(key, index);
    next += slots;
    return index;
  }

  /** Constant pool entry tags, as defined by the JVM class file specification. */
  private enum Tag {
    UTF8(1),
    INTEGER(3),
    FLOAT(4),
    LONG(5),
    DOUBLE(6),
    CLASS(7),
    STRING(8),
    FIELD_REFERENCE(9),
    METHOD_REFERENCE(10),
    NAME_AND_TYPE(12);

    private final int tag;

    Tag(final int tag) {
      this.tag = tag;
    }
  }

  @FunctionalInterface
  private interface Emit {
    void run() throws IOException;
  }
}
