package io.safelang.compiler.jvm;

import io.safelang.ModuleRegistry;
import io.safelang.ast.ASTNode;
import io.safelang.ast.AssertNode;
import io.safelang.ast.AssignmentNode;
import io.safelang.ast.BinaryExpressionNode;
import io.safelang.ast.CaseExpressionNode;
import io.safelang.ast.DoExpressionNode;
import io.safelang.ast.EnumDeclarationNode;
import io.safelang.ast.EnumPatternNode;
import io.safelang.ast.ExpressionStatementNode;
import io.safelang.ast.FieldAccessNode;
import io.safelang.ast.ForStatementNode;
import io.safelang.ast.FunctionCallNode;
import io.safelang.ast.FunctionDeclarationNode;
import io.safelang.ast.IfExpressionNode;
import io.safelang.ast.IndexAccessNode;
import io.safelang.ast.IndexAssignmentNode;
import io.safelang.ast.LambdaNode;
import io.safelang.ast.ListLiteralNode;
import io.safelang.ast.LiteralNode;
import io.safelang.ast.MapLiteralNode;
import io.safelang.ast.ObjectCreationNode;
import io.safelang.ast.ProgramNode;
import io.safelang.ast.RangeNode;
import io.safelang.ast.ReturnNode;
import io.safelang.ast.SetLiteralNode;
import io.safelang.ast.StringInterpolationNode;
import io.safelang.ast.TupleLiteralNode;
import io.safelang.ast.TypeDeclarationNode;
import io.safelang.ast.UnaryExpressionNode;
import io.safelang.ast.VariableDeclarationNode;
import io.safelang.ast.VariableReferenceNode;
import io.safelang.ast.WhileStatementNode;
import io.safelang.runtime.BuiltinRegistry;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Deque;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Translates a parsed SAFE program into a single JVM class. Every SAFE function becomes a {@code
 * static SAFEValue} method; top-level statements become {@code main}. All values are represented as
 * {@link io.safelang.runtime.SAFEValue} references and every runtime operation is routed through
 * the {@link JvmRuntime} facade, so generated bytecode references only ordinary class methods.
 *
 * <p>Each function uses a single epilogue: {@code return} stores the value into a result slot and
 * jumps to it, so there is exactly one {@code areturn} and no unreachable code — which keeps the
 * legacy (frame-less) verifier happy.
 *
 * <p>Imported stdlib/module functions are linked in by compiling each referenced module function
 * into the same class on demand (a worklist), with name resolution following the interpreter's
 * rules per module namespace. Constructs not yet handled (first-class functions, a few deep stdlib
 * parser modules) raise {@link JvmCompileException} rather than emit silently wrong code.
 */
final class JvmCodeGenerator {

  private static final String VALUE = "Lio/safelang/runtime/SAFEValue;";
  private static final String VALUE_CLASS = "io/safelang/runtime/SAFEValue";
  private static final String RUNTIME = "io/safelang/compiler/jvm/JvmRuntime";
  private static final String ITERATOR = "Ljava/util/Iterator;";
  private static final String LAMBDA_DESCRIPTOR =
      "([Lio/safelang/runtime/SAFEValue;[Lio/safelang/runtime/SAFEValue;)Lio/safelang/runtime/SAFEValue;";
  private final String name;
  private final ClassWriter writer;
  private final ModuleRegistry registry;
  private final Map<String, FunctionDeclarationNode> programFunctions = new HashMap<>();
  private final List<EnumDeclarationNode> programEnums = new ArrayList<>();
  private final Map<String, List<String>> fields = new HashMap<>();
  private final Map<String, Map<String, FunctionDeclarationNode>> moduleFunctions = new HashMap<>();
  private final Map<String, Collection<EnumDeclarationNode>> moduleEnums = new HashMap<>();
  private final Deque<Pending> worklist = new ArrayDeque<>();
  private final Set<String> queued = new HashSet<>();
  private final Deque<LambdaPending> lambdas = new ArrayDeque<>();
  private ProgramNode main;
  private MethodEmitter emitter;
  private ConstantPool pool;
  private Deque<Map<String, Integer>> scopes;
  private int slot;
  private int epilogue;
  private String module; // null while compiling the main program; module name otherwise
  private boolean isTopLevel; // true only while compiling main's top-level statements
  private int lambdaCount;

  JvmCodeGenerator(final String name, final ModuleRegistry registry) {
    this.name = name;
    this.registry = registry;
    this.writer = new ClassWriter(name, "java/lang/Object");
  }

  private static String descriptor(final int arity) {
    return "(" + VALUE.repeat(arity) + ")" + VALUE;
  }

  private static List<String> fields(final TypeDeclarationNode type) {
    final var names = new ArrayList<String>();
    for (final var field : type.fields()) {
      names.add(field.name());
    }
    return names;
  }

  byte[] generate(final ProgramNode program) {
    this.main = program;
    for (final var declaration : program.declarations()) {
      switch (declaration) {
        case FunctionDeclarationNode function -> programFunctions.put(function.name(), function);
        case EnumDeclarationNode enumeration -> programEnums.add(enumeration);
        case TypeDeclarationNode type -> {
          final var names = new ArrayList<String>();
          for (final var field : type.fields()) {
            names.add(field.name());
          }
          fields.put(type.name(), names);
        }
        default -> {}
      }
    }
    for (final var declaration : program.declarations()) {
      if (declaration instanceof FunctionDeclarationNode function) {
        function(function, null, function.name());
      }
    }
    program(program);
    // Drain transitively-referenced module functions and lambdas discovered during compilation.
    while (!worklist.isEmpty() || !lambdas.isEmpty()) {
      while (!worklist.isEmpty()) {
        final var pending = worklist.poll();
        function(pending.declaration(), pending.module(), pending.mangled());
      }
      while (!lambdas.isEmpty()) {
        lambda(lambdas.poll());
      }
    }
    return writer.toBytes();
  }

  private void function(
      final FunctionDeclarationNode function, final String owner, final String mangled) {
    final var parameters = function.parameters();
    this.module = owner;
    this.isTopLevel = false;
    begin(new MethodEmitter(parameters.size()));
    for (var index = 0; index < parameters.size(); index++) {
      scopes.peek().put(parameters.get(index).name(), index);
    }
    slot = emitter.reserve(1);
    epilogue = emitter.label();
    runtime("nothing", "()" + VALUE);
    emitter.storeReference(slot);

    if (function.hasRequires()) {
      value(function.requires());
      emitter.loadConstant(pool.string(function.name()));
      runtime("requires", "(" + VALUE + "Ljava/lang/String;)V");
    }
    if (function.hasDecreases()) {
      emitter.loadConstant(pool.string(function.name()));
      value(function.decreases());
      runtime("measureOf", "(" + VALUE + ")J");
      runtime("pushMeasure", "(Ljava/lang/String;J)V");
    }

    for (final var statement : function.body()) {
      exec(statement);
    }

    emitter.mark(epilogue);
    if (function.hasEnsures()) {
      scopes.peek().put("result", slot);
      value(function.ensures());
      emitter.loadConstant(pool.string(function.name()));
      runtime("ensures", "(" + VALUE + "Ljava/lang/String;)V");
    }
    if (function.hasDecreases()) {
      emitter.loadConstant(pool.string(function.name()));
      runtime("popMeasure", "(Ljava/lang/String;)V");
    }
    emitter.loadReference(slot);
    emitter.returnReference();
    writer.method(
        ClassWriter.ACC_PUBLIC | ClassWriter.ACC_STATIC,
        mangled,
        descriptor(parameters.size()),
        emitter);
  }

  private void lambda(final LambdaPending pending) {
    this.module = pending.module();
    this.isTopLevel = false;
    begin(new MethodEmitter(2)); // slot 0: captures array, slot 1: args array
    final var captures = pending.captures();
    for (var index = 0; index < captures.size(); index++) {
      emitter.loadReference(0);
      emitter.intConstant(index);
      emitter.arrayLoadReference();
      emitter.storeReference(define(captures.get(index)));
    }
    final var parameters = pending.node().parameters();
    for (var index = 0; index < parameters.size(); index++) {
      emitter.loadReference(1);
      emitter.intConstant(index);
      emitter.arrayLoadReference();
      emitter.storeReference(define(parameters.get(index).name()));
    }
    value(pending.node().body());
    emitter.returnReference();
    writer.method(
        ClassWriter.ACC_PUBLIC | ClassWriter.ACC_STATIC,
        pending.mangled(),
        LAMBDA_DESCRIPTOR,
        emitter);
  }

  private void program(final ProgramNode program) {
    this.module = null;
    this.isTopLevel = true;
    begin(new MethodEmitter(1));
    emitter.loadConstant(pool.classDefinition(name));
    runtime("program", "(Ljava/lang/Class;)V");
    emitter.loadReference(0);
    runtime("arguments", "([Ljava/lang/String;)V");
    for (final var declaration : program.declarations()) {
      if (declaration instanceof VariableDeclarationNode) {
        exec(declaration);
      }
    }
    for (final var statement : program.statements()) {
      exec(statement);
    }
    runtime("cleanup", "()V");
    emitter.returnVoid();
    writer.method(
        ClassWriter.ACC_PUBLIC | ClassWriter.ACC_STATIC, "main", "([Ljava/lang/String;)V", emitter);
  }

  private void begin(final MethodEmitter fresh) {
    this.emitter = fresh;
    this.pool = writer.pool();
    this.scopes = new ArrayDeque<>();
    this.scopes.push(new HashMap<>());
  }

  private void exec(final ASTNode node) {
    switch (node) {
      case ReturnNode ret -> {
        if (ret.hasExpression()) {
          value(ret.expression());
        } else {
          runtime("nothing", "()" + VALUE);
        }
        emitter.storeReference(slot);
        emitter.jump(epilogue);
      }
      case VariableDeclarationNode declaration -> {
        if (declaration.hasInitializer()) {
          value(declaration.initializer());
        } else {
          runtime("nothing", "()" + VALUE);
        }
        emitter.storeReference(define(declaration.name()));
      }
      case AssignmentNode assignment -> {
        if (assignment.parts().size() != 1) {
          throw new JvmCompileException("Field assignment is not yet supported in the JVM backend");
        }
        value(assignment.value());
        emitter.storeReference(lookup(assignment.parts().getFirst()));
      }
      case IndexAssignmentNode assignment -> {
        value(assignment.container());
        array(assignment.indices());
        value(assignment.value());
        runtime("store", "(" + VALUE + "[" + VALUE + VALUE + ")V");
      }
      case ForStatementNode loop -> forLoop(loop);
      case WhileStatementNode loop -> whileLoop(loop);
      case ExpressionStatementNode statement -> {
        value(statement.expression());
        emitter.pop();
      }
      default -> {
        value(node);
        emitter.pop();
      }
    }
  }

  private void forLoop(final ForStatementNode loop) {
    value(loop.iterable());
    runtime("elements", "(" + VALUE + ")" + ITERATOR);
    final var iterator = emitter.reserve(1);
    emitter.storeReference(iterator);

    scopes.push(new HashMap<>());
    final var variable = define(loop.variable());
    final var top = emitter.label();
    final var done = emitter.label();

    emitter.mark(top);
    emitter.loadReference(iterator);
    runtime("hasNext", "(" + ITERATOR + ")Z");
    emitter.ifEqual(done);
    emitter.loadReference(iterator);
    runtime("next", "(" + ITERATOR + ")" + VALUE);
    emitter.storeReference(variable);
    for (final var statement : loop.body()) {
      exec(statement);
    }
    emitter.jump(top);
    emitter.mark(done);
    scopes.pop();
  }

  private void whileLoop(final WhileStatementNode loop) {
    value(loop.bound());
    runtime("bound", "(" + VALUE + ")J");
    final var limit = emitter.reserve(2);
    emitter.storeLong(limit);
    emitter.longZero();
    final var counter = emitter.reserve(2);
    emitter.storeLong(counter);

    final var top = emitter.label();
    final var done = emitter.label();
    scopes.push(new HashMap<>());
    emitter.mark(top);
    emitter.loadLong(counter);
    emitter.loadLong(limit);
    emitter.compareLong();
    emitter.ifGreaterEqual(done); // counter >= limit
    value(loop.condition());
    runtime("truth", "(" + VALUE + ")Z");
    emitter.ifEqual(done); // condition is false
    for (final var statement : loop.body()) {
      exec(statement);
    }
    emitter.loadLong(counter);
    emitter.longOne();
    emitter.addLong();
    emitter.storeLong(counter);
    emitter.jump(top);
    emitter.mark(done);
    scopes.pop();
  }

  private void value(final ASTNode node) {
    switch (node) {
      case LiteralNode literal -> literal(literal);
      case VariableReferenceNode reference -> reference(reference);
      case BinaryExpressionNode binary -> binary(binary);
      case UnaryExpressionNode unary -> unary(unary);
      case FunctionCallNode call -> call(call);
      case IfExpressionNode conditional -> conditional(conditional);
      case DoExpressionNode block -> doBlock(block);
      case ListLiteralNode literal -> collection("list", literal.elements());
      case SetLiteralNode literal -> collection("set", literal.elements());
      case TupleLiteralNode literal -> collection("tuple", literal.elements());
      case MapLiteralNode literal -> mapLiteral(literal);
      case IndexAccessNode access -> {
        value(access.container());
        value(access.index());
        runtime("index", "(" + VALUE + VALUE + ")" + VALUE);
      }
      case StringInterpolationNode interpolation -> {
        array(interpolation.parts());
        runtime("interpolate", "([" + VALUE + ")" + VALUE);
      }
      case AssertNode assertion -> assertion(assertion);
      case ObjectCreationNode creation -> objectCreation(creation);
      case FieldAccessNode access -> {
        value(access.receiver());
        emitter.loadConstant(pool.string(access.field()));
        runtime("field", "(" + VALUE + "Ljava/lang/String;)" + VALUE);
      }
      case CaseExpressionNode caseExpression -> caseExpression(caseExpression);
      case LambdaNode lambda -> lambdaValue(lambda);
      case RangeNode range -> {
        value(range.start());
        value(range.end());
        if (range.hasStep()) {
          value(range.step());
        } else {
          emitter.loadConstant2(pool.longValue(1L));
          runtime("integer", "(J)" + VALUE);
        }
        runtime("range", "(" + VALUE + VALUE + VALUE + ")" + VALUE);
      }
      default ->
          throw new JvmCompileException(
              "Unsupported expression in JVM backend: " + node.getClass().getSimpleName());
    }
  }

  private void collection(final String kind, final List<ASTNode> elements) {
    array(elements);
    runtime(kind, "([" + VALUE + ")" + VALUE);
  }

  private void mapLiteral(final MapLiteralNode literal) {
    final var keys = new ArrayList<ASTNode>();
    final var values = new ArrayList<ASTNode>();
    for (final var entry : literal.entries()) {
      keys.add(entry.key());
      values.add(entry.value());
    }
    array(keys);
    array(values);
    runtime("map", "([" + VALUE + "[" + VALUE + ")" + VALUE);
  }

  private void assertion(final AssertNode assertion) {
    value(assertion.condition());
    if (assertion.hasMessage()) {
      value(assertion.message());
    } else {
      runtime("nothing", "()" + VALUE);
    }
    runtime("assertion", "(" + VALUE + VALUE + ")" + VALUE);
  }

  private void objectCreation(final ObjectCreationNode creation) {
    final var fields = fieldsOf(module, creation.type());
    if (fields == null) {
      throw new JvmCompileException("Undefined type in JVM backend: " + creation.type());
    }
    final var assigned = new HashMap<String, ASTNode>();
    for (final var field : creation.fields()) {
      assigned.put(field.field(), field.value());
    }
    emitter.loadConstant(pool.string(creation.type()));
    stringArray(fields);
    emitter.intConstant(fields.size());
    emitter.newReferenceArray(pool.classDefinition(VALUE_CLASS));
    for (var index = 0; index < fields.size(); index++) {
      emitter.dup();
      emitter.intConstant(index);
      final var expression = assigned.get(fields.get(index));
      if (expression != null) {
        value(expression);
      } else {
        runtime("nothing", "()" + VALUE);
      }
      emitter.arrayStoreReference();
    }
    runtime("object", "(Ljava/lang/String;[Ljava/lang/String;[" + VALUE + ")" + VALUE);
  }

  private void caseExpression(final CaseExpressionNode expression) {
    value(expression.subject());
    final var subject = emitter.reserve(1);
    emitter.storeReference(subject);
    final var end = emitter.label();

    for (final var branch : expression.branches()) {
      final var next = emitter.label();
      scopes.push(new HashMap<>());
      if (branch.isWildcard()) {
        guard(branch.guard(), next);
      } else if (branch.pattern() instanceof EnumPatternNode pattern) {
        emitter.loadReference(subject);
        emitter.loadConstant(pool.string(pattern.variant()));
        runtime("variantMatches", "(" + VALUE + "Ljava/lang/String;)Z");
        emitter.ifEqual(next);
        final var bindings = pattern.bindings();
        for (var index = 0; index < bindings.size(); index++) {
          emitter.loadReference(subject);
          emitter.intConstant(index);
          runtime("datum", "(" + VALUE + "I)" + VALUE);
          emitter.storeReference(define(bindings.get(index)));
        }
        guard(branch.guard(), next);
      } else {
        emitter.loadReference(subject);
        value(branch.pattern());
        runtime("equal", "(" + VALUE + VALUE + ")Z");
        emitter.ifEqual(next);
        guard(branch.guard(), next);
      }
      value(branch.result());
      emitter.jump(end);
      emitter.mark(next);
      scopes.pop();
    }

    if (expression.hasFallback()) {
      value(expression.fallback());
    } else {
      runtime("nothing", "()" + VALUE);
    }
    emitter.mark(end);
  }

  /**
   * Materialize a lambda as a function value. Captures every enclosing local by value (a superset
   * of the lambda's free variables — harmless since SAFE closures capture by value) and emits the
   * body as a separate static method dispatched reflectively at call time.
   */
  private void lambdaValue(final LambdaNode lambda) {
    final var captures = new ArrayList<String>();
    final var seen = new HashSet<String>();
    for (final var scope : scopes) {
      for (final var name : scope.keySet()) {
        if (seen.add(name)) {
          captures.add(name);
        }
      }
    }
    final var mangled = "lambda$" + lambdaCount++;
    lambdas.add(new LambdaPending(mangled, lambda, captures, module));

    emitter.loadConstant(pool.string(mangled));
    emitter.intConstant(captures.size());
    emitter.newReferenceArray(pool.classDefinition(VALUE_CLASS));
    for (var index = 0; index < captures.size(); index++) {
      emitter.dup();
      emitter.intConstant(index);
      emitter.loadReference(lookup(captures.get(index)));
      emitter.arrayStoreReference();
    }
    runtime("closure", "(Ljava/lang/String;[" + VALUE + ")" + VALUE);
  }

  private void guard(final ASTNode condition, final int next) {
    if (condition == null) {
      return;
    }
    value(condition);
    runtime("truth", "(" + VALUE + ")Z");
    emitter.ifEqual(next);
  }

  private void stringArray(final List<String> values) {
    emitter.intConstant(values.size());
    emitter.newReferenceArray(pool.classDefinition("java/lang/String"));
    for (var index = 0; index < values.size(); index++) {
      emitter.dup();
      emitter.intConstant(index);
      emitter.loadConstant(pool.string(values.get(index)));
      emitter.arrayStoreReference();
    }
  }

  private void literal(final LiteralNode literal) {
    switch (literal) {
      case LiteralNode.IntLiteral value -> {
        emitter.loadConstant2(pool.longValue(value.value()));
        runtime("integer", "(J)" + VALUE);
      }
      case LiteralNode.UintLiteral value -> {
        emitter.loadConstant2(pool.longValue(value.value()));
        runtime("unsigned", "(J)" + VALUE);
      }
      case LiteralNode.FloatLiteral value -> {
        emitter.loadConstant2(pool.doubleValue(value.value()));
        runtime("decimal", "(D)" + VALUE);
      }
      case LiteralNode.StringLiteral value -> {
        emitter.loadConstant(pool.string(value.value()));
        runtime("text", "(Ljava/lang/String;)" + VALUE);
      }
      case LiteralNode.BoolLiteral value -> {
        emitter.intConstant(value.value() ? 1 : 0);
        runtime("bool", "(Z)" + VALUE);
      }
    }
  }

  private void reference(final VariableReferenceNode reference) {
    final var parts = reference.parts();
    // Dotted module access: `math.PI` parses as parts=[math, PI] with no colon prefix.
    if (!reference.hasPrefix()
        && parts.size() > 1
        && registry != null
        && registry.has(parts.get(0))
        && !isLocal(parts.get(0))) {
      loadSingle(parts.get(0), parts.get(1), true);
      for (var index = 2; index < parts.size(); index++) {
        emitter.loadConstant(pool.string(parts.get(index)));
        runtime("field", "(" + VALUE + "Ljava/lang/String;)" + VALUE);
      }
      return;
    }
    final var owner = reference.hasPrefix() ? reference.prefix() : module;
    loadSingle(owner, parts.getFirst(), reference.hasPrefix());
    for (var index = 1; index < parts.size(); index++) {
      emitter.loadConstant(pool.string(parts.get(index)));
      runtime("field", "(" + VALUE + "Ljava/lang/String;)" + VALUE);
    }
  }

  /** Load a single named value: a local, a module constant, or a unit enum variant. */
  private void loadSingle(final String owner, final String name, final boolean prefixed) {
    if (!prefixed && isLocal(name)) {
      emitter.loadReference(lookup(name));
      return;
    }
    final var constant = constantOf(owner, name);
    if (constant != null && constant.hasInitializer()) {
      inline(owner, constant.initializer());
      return;
    }
    if (enumTypeOf(owner, name) != null && isUnitVariant(owner, name)) {
      construct(enumTypeOf(owner, name), name, List.of());
      return;
    }
    if (!prefixed) {
      emitter.loadReference(lookup(name));
      return;
    }
    throw new JvmCompileException(
        "Unsupported module reference in JVM backend: " + owner + ":" + name);
  }

  /** Inline a module constant's initializer, resolved in that module's namespace. */
  private void inline(final String owner, final ASTNode initializer) {
    final var saved = module;
    module = owner;
    try {
      value(initializer);
    } finally {
      module = saved;
    }
  }

  private void binary(final BinaryExpressionNode binary) {
    final var operator = binary.operator();
    if ("&&".equals(operator) || "||".equals(operator)) {
      shortCircuit(binary);
      return;
    }
    emitter.loadConstant(pool.string(operator));
    value(binary.left());
    value(binary.right());
    runtime("binary", "(Ljava/lang/String;" + VALUE + VALUE + ")" + VALUE);
  }

  private void shortCircuit(final BinaryExpressionNode binary) {
    final var conjunction = "&&".equals(binary.operator());
    final var shortcut = emitter.label();
    final var end = emitter.label();

    value(binary.left());
    runtime("truth", "(" + VALUE + ")Z");
    if (conjunction) {
      emitter.ifEqual(shortcut); // false short-circuits an &&
    } else {
      emitter.ifNotEqual(shortcut); // true short-circuits an ||
    }
    value(binary.right());
    runtime("truth", "(" + VALUE + ")Z");
    if (conjunction) {
      emitter.ifEqual(shortcut);
    } else {
      emitter.ifNotEqual(shortcut);
    }
    emitter.intConstant(conjunction ? 1 : 0);
    runtime("bool", "(Z)" + VALUE);
    emitter.jump(end);
    emitter.mark(shortcut);
    emitter.intConstant(conjunction ? 0 : 1);
    runtime("bool", "(Z)" + VALUE);
    emitter.mark(end);
  }

  private void unary(final UnaryExpressionNode unary) {
    value(unary.operand());
    switch (unary.operator()) {
      case "!" -> runtime("not", "(" + VALUE + ")" + VALUE);
      case "-" -> runtime("negate", "(" + VALUE + ")" + VALUE);
      case "~" -> runtime("complement", "(" + VALUE + ")" + VALUE);
      default -> throw new JvmCompileException("Unknown unary operator: " + unary.operator());
    }
  }

  private void call(final FunctionCallNode call) {
    final var name = call.name();
    final var arguments = call.arguments();

    if (call.hasPrefix()) {
      final var prefix = call.prefix();
      final var declaration = registry == null ? null : registry.function(prefix, name);
      if (declaration != null) {
        invokeUser(prefix, declaration, arguments);
        return;
      }
      final var enumType = enumTypeOf(prefix, name);
      if (enumType != null) {
        construct(enumType, name, arguments);
        return;
      }
      if (BuiltinRegistry.isBuiltin(name)) {
        builtin(name, arguments);
        return;
      }
      throw new JvmCompileException(
          "Unsupported module call in JVM backend: " + prefix + ":" + name);
    }

    // Unprefixed call, resolved in the current module's namespace. Inside a function body builtins
    // take precedence over same-named functions (mirroring the interpreter at call depth > 0); at
    // the top level a user/module function may shadow a builtin.
    final var declaration = localFunction(name);
    if (isTopLevel && declaration != null) {
      invokeUser(module, declaration, arguments);
      return;
    }
    if (BuiltinRegistry.isBuiltin(name)) {
      builtin(name, arguments);
      return;
    }
    if (declaration != null) {
      invokeUser(module, declaration, arguments);
      return;
    }
    final var enumType = enumTypeOf(module, name);
    if (enumType != null) {
      construct(enumType, name, arguments);
      return;
    }
    if (isLocal(name)) {
      // Call-through-value: `name` holds a function value (lambda or passed-in callback).
      emitter.loadReference(lookup(name));
      array(arguments);
      runtime("invoke", "(" + VALUE + "[" + VALUE + ")" + VALUE);
      return;
    }
    throw new JvmCompileException("Unsupported call in JVM backend: " + name);
  }

  private void invokeUser(
      final String owner,
      final FunctionDeclarationNode declaration,
      final List<ASTNode> arguments) {
    final var parameters = declaration.parameters();
    if (arguments.size() > parameters.size()) {
      throw new JvmCompileException(
          "JVM backend: too many arguments for "
              + declaration.name()
              + " (got "
              + arguments.size()
              + ", expected "
              + parameters.size()
              + ")");
    }
    for (var index = arguments.size(); index < parameters.size(); index++) {
      if (!parameters.get(index).hasDefault()) {
        throw new JvmCompileException(
            "JVM backend: missing argument "
                + parameters.get(index).name()
                + " for "
                + declaration.name());
      }
    }
    final var mangled = enqueue(owner, declaration);
    for (final var argument : arguments) {
      value(argument);
    }
    // Fill defaults, evaluated in the callee's module namespace (a default may reference that
    // module's enums/constants, e.g. `Format mode = JSON`).
    for (var index = arguments.size(); index < parameters.size(); index++) {
      inline(owner, parameters.get(index).initial());
    }
    final var signature = descriptor(parameters.size());
    emitter.invokeStatic(pool.method(name, mangled, signature), signature);
  }

  private void builtin(final String name, final List<ASTNode> arguments) {
    emitter.loadConstant(pool.string(name));
    array(arguments);
    runtime("call", "(Ljava/lang/String;[" + VALUE + ")" + VALUE);
  }

  private void construct(final String enumType, final String variant, final List<ASTNode> data) {
    emitter.loadConstant(pool.string(enumType));
    emitter.loadConstant(pool.string(variant));
    array(data);
    runtime("enumeration", "(Ljava/lang/String;Ljava/lang/String;[" + VALUE + ")" + VALUE);
  }

  private void array(final List<ASTNode> elements) {
    emitter.intConstant(elements.size());
    emitter.newReferenceArray(pool.classDefinition(VALUE_CLASS));
    for (var index = 0; index < elements.size(); index++) {
      emitter.dup();
      emitter.intConstant(index);
      value(elements.get(index));
      emitter.arrayStoreReference();
    }
  }

  private void conditional(final IfExpressionNode conditional) {
    final var otherwise = emitter.label();
    final var end = emitter.label();
    value(conditional.condition());
    runtime("truth", "(" + VALUE + ")Z");
    emitter.ifEqual(otherwise);
    value(conditional.then());
    emitter.jump(end);
    emitter.mark(otherwise);
    if (conditional.hasOtherwise()) {
      value(conditional.otherwise());
    } else {
      runtime("nothing", "()" + VALUE);
    }
    emitter.mark(end);
  }

  private void doBlock(final DoExpressionNode block) {
    scopes.push(new HashMap<>());
    for (final var statement : block.statements()) {
      exec(statement);
    }
    value(block.expression());
    scopes.pop();
  }

  private void runtime(final String name, final String descriptor) {
    emitter.invokeStatic(pool.method(RUNTIME, name, descriptor), descriptor);
  }

  private int define(final String name) {
    final var slot = emitter.reserve(1);
    assert scopes.peek() != null;
    scopes.peek().put(name, slot);
    return slot;
  }

  private int lookup(final String name) {
    for (final var scope : scopes) {
      final var slot = scope.get(name);
      if (slot != null) {
        return slot;
      }
    }
    throw new JvmCompileException("Undefined variable in JVM backend: " + name);
  }

  private boolean isLocal(final String name) {
    for (final var scope : scopes) {
      if (scope.containsKey(name)) {
        return true;
      }
    }
    return false;
  }

  private String enqueue(final String owner, final FunctionDeclarationNode declaration) {
    final var mangled = owner == null ? declaration.name() : owner + "$" + declaration.name();
    if (owner != null && queued.add(mangled)) {
      worklist.add(new Pending(owner, declaration, mangled));
    }
    return mangled;
  }

  private FunctionDeclarationNode localFunction(final String name) {
    return module == null ? programFunctions.get(name) : moduleFunctions(module).get(name);
  }

  /**
   * All functions a module can call by bare name — its own public and private declarations. The
   * registry only indexes public functions (for qualified imports), so private helpers are gathered
   * directly from the module's program declarations.
   */
  private Map<String, FunctionDeclarationNode> moduleFunctions(final String owner) {
    return moduleFunctions.computeIfAbsent(
        owner,
        key -> {
          final var map = new HashMap<String, FunctionDeclarationNode>();
          final var program = registry == null ? null : registry.program(key);
          if (program != null) {
            for (final var declaration : program.declarations()) {
              if (declaration instanceof FunctionDeclarationNode function) {
                map.put(function.name(), function);
              }
            }
          }
          return map;
        });
  }

  private VariableDeclarationNode constantOf(final String owner, final String name) {
    if (owner == null || registry == null) {
      return null;
    }
    return registry.constant(owner, name);
  }

  private List<String> fieldsOf(final String owner, final String type) {
    final var own = ownFields(owner, type);
    if (own != null) {
      return own;
    }
    for (final var imported : importsOf(owner)) {
      final var fields = registry.types(imported).get(type);
      if (fields != null) {
        return fields(fields);
      }
    }
    return null;
  }

  private List<String> ownFields(final String owner, final String type) {
    if (owner == null) {
      return fields.get(type);
    }
    final var declaration = registry == null ? null : registry.types(owner).get(type);
    return declaration == null ? null : fields(declaration);
  }

  private String enumTypeOf(final String owner, final String variant) {
    final var match = findVariant(owner, variant);
    return match == null ? null : match.type();
  }

  private boolean isUnitVariant(final String owner, final String variant) {
    final var match = findVariant(owner, variant);
    return match != null && !match.variant().hasFields();
  }

  /** Find an enum variant by name in the owner's namespace and its directly-imported modules. */
  private EnumMatch findVariant(final String owner, final String name) {
    final var direct = matchIn(enumsOf(owner), name);
    if (direct != null) {
      return direct;
    }
    for (final var imported : importsOf(owner)) {
      final var match = matchIn(enumsOf(imported), name);
      if (match != null) {
        return match;
      }
    }
    return null;
  }

  private EnumMatch matchIn(final Collection<EnumDeclarationNode> enums, final String name) {
    for (final var enumeration : enums) {
      for (final var candidate : enumeration.variants()) {
        if (candidate.name().equals(name)) {
          return new EnumMatch(enumeration.name(), candidate);
        }
      }
    }
    return null;
  }

  private Collection<EnumDeclarationNode> enumsOf(final String owner) {
    if (owner == null) {
      return programEnums;
    }
    // Gather from the module's declarations (incl. private enums like json's `Parsed`); the
    // registry
    // only indexes public enums.
    return moduleEnums.computeIfAbsent(
        owner,
        key -> {
          final var found = new ArrayList<EnumDeclarationNode>();
          final var program = registry == null ? null : registry.program(key);
          if (program != null) {
            for (final var declaration : program.declarations()) {
              if (declaration instanceof EnumDeclarationNode enumeration) {
                found.add(enumeration);
              }
            }
          }
          return found;
        });
  }

  private List<String> importsOf(final String owner) {
    final var program = owner == null ? main : (registry == null ? null : registry.program(owner));
    if (program == null) {
      return List.of();
    }
    final var names = new ArrayList<String>();
    for (final var imported : program.imports()) {
      names.add(imported.module());
    }
    return names;
  }

  private record Pending(String module, FunctionDeclarationNode declaration, String mangled) {}

  private record EnumMatch(String type, io.safelang.ast.EnumVariantNode variant) {}

  private record LambdaPending(
      String mangled, LambdaNode node, List<String> captures, String module) {}
}
